immune-cell-census: immune-cell-census.mtx.zip
	unzip $<

immune-cell-census.mtx.zip:
	curl -L "https://data.humancellatlas.org/project-assets/project-matrices/cc95ff89-2e68-4a08-a234-480eca21ce79.homo_sapiens.mtx.zip" -o $@

immune-cell-census.loom:
	curl -L "https://data.humancellatlas.org/project-assets/project-matrices/cc95ff89-2e68-4a08-a234-480eca21ce79.homo_sapiens.loom" -o $@
