#+TITLE: Hierarchical NMF
#+SETUPFILE: setup.org

* Introduction

  Matthew Stephens suggested that rather than aiming for sparse NMF/topic
  models (for interpretability), we might aim for topic models in which topics
  do not deviate from the mean at most genes. This idea suggests a hierarchical
  model\(
  \DeclareMathOperator\Pois{Poisson}
  \DeclareMathOperator\Gam{Gamma}
  \DeclareMathOperator\Mult{Multinomial}
  \newcommand\E[1]{\left\langle #1 \right\rangle}
  \newcommand\const{\mathrm{const}}
  \newcommand\ml{\mathbf{L}}
  \newcommand\vmu{\boldsymbol{\mu}}
  \newcommand\mphi{\boldsymbol{\Phi}}
  \)

  \begin{align*}
    x_{ij} \mid s_i, \lambda_{ij} &\sim \Pois(s_i \lambda_{ij})\\
    \lambda_{ij} &= \sum_k l_{ik} f_{jk}\\
    f_{jk} &\sim \Gam(\phi_{jk}^{-1}, \phi_{jk}^{-1}\mu_j^{-1}),
  \end{align*}

  where the Gamma distribution is parameterized by shape and rate. In this
  parameterization, \(\E{f_{jk}} = \mu_j\) and \(V[f_{jk}] = \mu_j^2
  \phi_{jk}\).

  The inference goal is to estimate \(\ml = [l_{ik}]\),
  \(\vmu = [\mu_j]\), \(\mphi = [\phi_{jk}]\) via
  variational EM. Here, we explore whether a re-parameterization makes this
  model easier to fit.

* Variational EM

  [[https://dx.doi.org/10.1155/2009/785152][Cemgil 2009]] describes how to
  perform VI in this family of models. First, augment the model

  \begin{align*}
    x_{ij} &= \sum_{k=1}^{K} z_{ijk}\\
    z_{ijk} \mid \lambda_{ijk} &\sim \Pois(s_i \lambda_{ijk})\\
    \lambda_{ijk} &= l_{ik} f_{jk}\\
    f_{jk} &\sim \Gam(\phi_{jk}^{-1}, \phi_{jk}^{-1}\mu_j^{-1}).
  \end{align*}
  
  Then, the log joint is

  \begin{multline}
    \ln p(\cdot) = \sum_{i,j,k} \left[z_{ijk} \ln(s_i l_{ik} f_{jk}) - s_i l_{ik} f_{jk} - \ln\Gamma(z_{ijk} + 1)\right]\\
    + \sum_{j, k} \left[\phi_{jk}^{-1} \ln(\phi_{jk}^{-1}\mu_j^{-1}) + (\phi_{jk}^{-1} - 1) \ln f_{jk} - \phi_{jk}^{-1}\mu_j^{-1} f_{jk} - \ln\Gamma(\phi_{jk}^{-1}) \right],
  \end{multline}

  and by a variational argument, we have

  \begin{align*}
    q^*(z_{ij1}, \ldots, z_{ijK}) &\propto \exp(\sum_k z_{ijk} (\ln(s_i l_{ik}) + \E{\ln f_{jk}}))\\
    &= \Mult(\cdot; x_{ij}, \frac{l_{i1} \exp(\E{\ln f_{j1}})}{\sum_t l_{it} \exp(\E{\ln f_{jt}})}, \ldots, \frac{l_{iK} \exp(\E{\ln f_{jK}})}{\sum_t l_{it} \exp(\E{\ln f_{jt}})})\\
    q^*(f_{jk}) &\propto \exp(\E{z_{ijk}} \ln f_{jk} - s_i l_{ik} f_{jk} + (\phi_{jk}^{-1} - 1) \ln f_{jk} - \phi_{jk}^{-1}\mu_j^{-1} f_{jk})\\
    &= \Gam(\E{z_{ijk}} + \phi_{jk}^{-1}, s_i l_{ik} + \phi_{jk}^{-1}\mu_j^{-1}).
  \end{align*}

* Alternative scheme

  Using the fact that Gamma distributions are closed under multiplication,
  write
  
  \begin{align*}
    x_{ij} \mid s_i, \lambda_{ij} &\sim \Pois(s_i \lambda_{ij})\\
    \lambda_{ij} &= \sum_{k=1}^K l_{ik} \mu_j u_{jk}\\
    u_{jk} &\sim \Gam(\phi_{jk}^{-1}, \phi_{jk}^{-1}),
  \end{align*}

  implying \(\lambda_{ij} \sim g_{ij}(\cdot)\). Then, the marginal log
  likelihood is

  \begin{equation*}
    \ln p(x_{ij} \mid \cdot) = x_{ij} \ln\left(\frac{s_i \sum_k l_{ik} \mu_j \phi_{jk}}{1 + s_i \sum_k l_{ik} \mu_j \phi_{jk}}\right) - \phi_{jk}^{-1} \ln(1 + s_i \mu_j\phi_{jk}) + \ln\Gamma(x_{ij} + \phi_{jk}^{-1}) - \ln\Gamma(x_{ij} + 1) - \ln \Gamma(\phi^{-1}),
  \end{equation*}

  suggesting estimating \(g_{ij}\) by maximizing the marginal log likelihood
  with respect to \(\ml, \vmu, \mphi\). Now [[*Variational EM][augment the
  model as above]]; then, the log joint is

  \begin{multline}
    \ln p(\cdot) = \sum_{i,j,k} \left[z_{ijk} \ln(s_i l_{ik} \mu_j u_{jk}) - s_i l_{ik} \mu_j u_{jk} - \ln\Gamma(z_{ijk} + 1)\right]\\
    + \sum_{j, k} \left[\phi_{jk}^{-1} \ln \phi_{jk}^{-1} + (\phi_{jk}^{-1} - 1) \ln u_{jk} - \phi_{jk}^{-1} u_{jk} - \ln\Gamma(\phi_{jk}^{-1}) \right].
  \end{multline}
  
  As argued previously (Gouvert et al. 2018),

  \[ p(z_{ij1}, \ldots, z_{ijK} \mid \cdot) = \Mult(x_{ij}, \frac{l_{i1} \mu_j}{\sum_t l_{it} \mu_j}, \ldots, \frac{l_{iK} \mu_j}{\sum_t l_{it} \mu_j}) \]

  and by a similar argument [[*Variational EM][as above]],

  \[ q^*(u_{jk}) = \Gam(\E{z_{ijk}} + \phi_{jk}^{-1}, s_i l_{ik} \mu_j + \phi_{jk}^{-1}). \]

